In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
sns.set_theme(style="darkgrid")

In [5]:
data = {
    "Square_Feet": np.random.randint(500, 3500, size=10),
    "Location": ["Rural", "Urban", "Suburban", "Rural", "Rural", "Urban", "Suburban", "Urban", "Rural", "Suburban"],
    "Price": np.random.uniform(low=1000, high=5000, size=10)
}

In [6]:
df = pd.DataFrame(data)
df.head()

   Square_Feet  Location        Price
0         2132     Rural  4492.140952
1         1122     Urban  2080.774305
2         2194  Suburban  4889.287115
3         2416     Rural  1645.584783
4         2004     Rural  4885.871842

In [7]:
df.describe()

       Square_Feet        Price
count    10.000000    10.000000
mean   2025.400000  3161.287366
std     694.297759  1409.374953
min    1051.000000  1574.394289
25%    1692.750000  1998.959886
50%    2068.000000  2920.695829
75%    2319.250000  4431.440967
max    3471.000000  4889.287115

In [12]:
avg_price_per_location = df.groupby('Location')['Price'].mean()
print(avg_price_per_location)

Location
Rural       3696.053732
Suburban    2974.716374
Urban       2634.836535
Name: Price, dtype: float64